openapi: 3.0.1
info:
  title: ZipLink API
  version: 1.0.0
servers:
  - url: /
paths:
  /api/shorten:
    get:
      summary: Shorten a URL with ZipLink
      description: Returns a shortened URL for a given long URL
      parameters:
        - name: url
          in: query
          description: The long URL to shorten
          required: true
          schema:
            type: string
        - name: alias
          in: query
          description: Change Alias
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortened_url:
                    type: string
                    description: The shortened URL
        400:
          description: Invalid request
          content: {}
        500:
          description: Server error
          content: {}
components: {}
